openapi: 3.0.0
info:
  contact:
    email: russell-laboe@outlook.com
    name: Russell Laboe
  title: Salesforce Platform REST API
  version: "56.0"
servers:
- description: API Base URL
  url: "{instanceUrl}/services/data/v{apiVersion}"
  variables:
    instanceUrl:
      default: https://myorg.lightning.force.com
      description: Salesforce server domain
    apiVersion:
      default: "56.0"
      description: Salesforce api version
security:
- oAuth: []
paths:
  /:
    get:
      description: "Lists available resources for the specified API version, including\
        \ resource name and URI."
      externalDocs:
        description: Salesforce Documentation
        url: https://developer.salesforce.com/docs/atlas.en-us.api_rest.meta/api_rest/resources_discoveryresource.htm
      operationId: getResources
      parameters:
      - explode: false
        in: header
        name: Accept-Encoding
        required: false
        schema:
          $ref: '#/components/schemas/EncodingType'
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema: {}
          description: Successful response
        "401":
          content: {}
          description: Unauthorized
        "400":
          content: {}
          description: Bad Request
      summary: List Available REST Resources
      tags:
      - Org
  /limits:
    get:
      description: "Lists information about limits in your org. For each limit, this\
        \ resource returns the maximum allocation and the remaining allocation based\
        \ on usage. This resource is available in REST API version 29.0 and later\
        \ for API users with the View Setup and Configuration permission."
      externalDocs:
        description: Salesforce Documentation
        url: https://developer.salesforce.com/docs/atlas.en-us.api_rest.meta/api_rest/resources_limits.htm
      operationId: getLimits
      parameters:
      - explode: false
        in: header
        name: Accept-Encoding
        required: false
        schema:
          $ref: '#/components/schemas/EncodingType'
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema: {}
          description: Successful response
        "401":
          content: {}
          description: Unauthorized
        "400":
          content: {}
          description: Bad Request
      summary: List Org Limits
      tags:
      - Org
  /sobjects:
    get:
      description: |-
        Lists the available objects and their metadata for your organization’s data. In addition, it provides the organization encoding, as well as the maximum batch size permitted in queries. For more information on encoding, see [Internationalization and Character Sets](https://developer.salesforce.com/docs/atlas.en-us.242.0.api.meta/api/implementation_considerations.htm#sforce_api_other_internationalization).
        You can use the If-Modified-Since or If-Unmodified-Since header with this resource. When using the If-Modified-Since header, if no available object’s metadata has changed since the provided date, a 304 Not Modified status code is returned with no response body.
      externalDocs:
        description: Salesforce Documentation
        url: https://developer.salesforce.com/docs/atlas.en-us.api_rest.meta/api_rest/resources_describeGlobal.htm
      operationId: getSObjects
      parameters:
      - explode: false
        in: header
        name: Accept-Encoding
        required: false
        schema:
          $ref: '#/components/schemas/EncodingType'
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/sObjectDescribes'
          description: Successful response
        "401":
          content: {}
          description: Unauthorized
        "400":
          content: {}
          description: Bad Request
      summary: Get a List of Objects
      tags:
      - SObject
  /sobjects/{sObject}:
    get:
      description: "Retrieves basic metadata for a specified object, including some\
        \ object properties, recent items, and URIs for other resources related to\
        \ the object. To retrieve the complete metadata for an object, use the (sObject\
        \ Describe)[https://developer.salesforce.com/docs/atlas.en-us.api_rest.meta/api_rest/resources_sobject_describe.htm]\
        \ resource."
      externalDocs:
        description: Salesforce Documentation
        url: https://developer.salesforce.com/docs/atlas.en-us.api_rest.meta/api_rest/resources_sobject_basic_info_get.htm
      operationId: GetBasicInfo
      parameters:
      - description: SObject name
        example: Contact
        explode: false
        in: path
        name: sObject
        required: true
        schema:
          type: string
        style: simple
      - explode: false
        in: header
        name: Accept-Encoding
        required: false
        schema:
          $ref: '#/components/schemas/EncodingType'
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                type: object
          description: Successful response
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errors'
          description: Unauthorized
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errors'
          description: Bad Request
      summary: Retrieve Object Metadata Using sObject Basic Information
      tags:
      - SObject
    post:
      description: Creates a new record for a specified object based on field values
        in the request body. You must specify values for required fields in the request
        body. Specifying values for other fields is optional.
      externalDocs:
        description: Salesforce Documentation
        url: https://developer.salesforce.com/docs/atlas.en-us.api_rest.meta/api_rest/resources_sobject_basic_info_post.htm
      operationId: createRecord
      parameters:
      - description: SObject name
        example: Contact
        explode: false
        in: path
        name: sObject
        required: true
        schema:
          type: string
        style: simple
      - explode: false
        in: header
        name: Content-Encoding
        required: false
        schema:
          $ref: '#/components/schemas/EncodingType'
        style: simple
      - explode: false
        in: header
        name: Accept-Encoding
        required: false
        schema:
          $ref: '#/components/schemas/EncodingType'
        style: simple
      requestBody:
        content:
          application/json:
            example:
              name: Express Logistics and Transport
            schema:
              type: object
        description: SObject record to insert
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/createRecordResult'
          description: Successful response
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errors'
          description: Unauthorized
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errors'
          description: Bad Request
      summary: Create Records Using sObject Basic Information
      tags:
      - SObject
  /sobjects/{sObject}/describe:
    get:
      description: |-
        Completely describes the individual metadata at all levels for the specified object. For example, this can be used to retrieve the fields, URLs, and child relationships for the Account object.
        For more information about the metadata that is retrieved, see [DescribesObjectResult](https://developer.salesforce.com/docs/atlas.en-us.242.0.api.meta/api/sforce_api_calls_describesobjects_describesobjectresult.htm) in the SOAP API Developers Guide.
        You can use the If-Modified-Since or If-Unmodified-Since header with this resource. When using the If-Modified-Since header, if no available object’s metadata has changed since the provided date, a 304 Not Modified status code is returned with no response body.
      externalDocs:
        description: Salesforce Documentation
        url: https://developer.salesforce.com/docs/atlas.en-us.api_rest.meta/api_rest/resources_sobject_describe.htm
      operationId: sObjectDescribe
      parameters:
      - description: SObject name
        example: Contact
        explode: false
        in: path
        name: sObject
        required: true
        schema:
          type: string
        style: simple
      - description: An optional header specifying a date and time. The request returns
          records that have been modified after that date and time.
        example: "Mon, 30 Nov 2020 08:34:54 MST"
        explode: false
        in: header
        name: If-Modified-Since
        required: false
        schema:
          type: string
        style: simple
      - description: An optional header specifying a date and time. The request returns
          records that have not been modified after that date and time.
        example: "Mon, 30 Nov 2020 08:34:54 MST"
        explode: false
        in: header
        name: If-Unmodified-Since
        required: false
        schema:
          type: string
        style: simple
      - explode: false
        in: header
        name: Accept-Encoding
        required: false
        schema:
          $ref: '#/components/schemas/EncodingType'
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/sObjectDescribe'
          description: Successful response
        "401":
          content: {}
          description: Unauthorized
        "400":
          content: {}
          description: Bad Request
      summary: Retrieve Metadata for an Object
      tags:
      - SObject
components:
  schemas:
    sObjectDescribe:
      example:
        mruEnabled: true
        updateable: true
        activateable: true
        childRelationships:
        - relationshipName: Accounts__r
          field: Primary_Contact__c
          deprecatedAndHidden: true
          junctionReferenceTo:
          - "{}"
          - "{}"
          junctionIdListNames:
          - "{}"
          - "{}"
          childSObject: Account
          cascadeDelete: true
          restrictedDelete: true
        - relationshipName: Accounts__r
          field: Primary_Contact__c
          deprecatedAndHidden: true
          junctionReferenceTo:
          - "{}"
          - "{}"
          junctionIdListNames:
          - "{}"
          - "{}"
          childSObject: Account
          cascadeDelete: true
          restrictedDelete: true
        recordTypeInfos:
        - defaultRecordTypeMapping: true
          urls:
            layout: /services/data/v56.0/sobjects/Contact/describe/layouts/012000000000000AAA
          recordTypeId: 012000000000000AAA
          available: true
          name: Master
          active: true
          developerName: Master
          master: true
        - defaultRecordTypeMapping: true
          urls:
            layout: /services/data/v56.0/sobjects/Contact/describe/layouts/012000000000000AAA
          recordTypeId: 012000000000000AAA
          available: true
          name: Master
          active: true
          developerName: Master
          master: true
        deprecatedAndHidden: true
        supportedScopes:
        - name: everything
          label: All contacts
        - name: everything
          label: All contacts
        searchLayoutable: true
        sobjectDescribeOption: FULL
        deletable: true
        replicateable: true
        actionOverrides:
        - formFactor: LARGE
          name: View
          pageId: 0M03b000000PGADCA4
          url: url
          isAvailableInTouch: true
        - formFactor: LARGE
          name: View
          pageId: 0M03b000000PGADCA4
          url: url
          isAvailableInTouch: true
        isSubtype: true
        lookupLayoutable: lookupLayoutable
        listviewable: listviewable
        mergeable: true
        urls: "{}"
        compactLayoutable: true
        feedEnabled: true
        extendsInterfaces: extendsInterfaces
        networkScopeFieldName: networkScopeFieldName
        customSetting: true
        isInterface: true
        implementedBy: implementedBy
        implementsInterfaces: implementsInterfaces
        extendedBy: extendedBy
        defaultImplementation: defaultImplementation
        deepCloneable: true
        layoutable: true
        custom: true
        associateParentEntity: associateParentEntity
        undeletable: true
        label: Contact
        keyPrefix: "3"
        searchable: true
        namedLayoutInfos:
        - ""
        - ""
        queryable: true
        createable: true
        retrieveable: true
        associateEntityType: associateEntityType
        hasSubtypes: true
        name: Contact
        fields:
        - defaultValue: defaultValue
          precision: 0
          compoundFieldName: compoundFieldName
          nameField: true
          type: id
          restrictedDelete: true
          relationshipName: relationshipName
          calculatedFormula: calculatedFormula
          controllerName: controllerName
          namePointing: true
          defaultValueFormula: defaultValueFormula
          calculated: true
          writeRequiresMasterRead: true
          inlineHelpText: inlineHelpText
          picklistValues:
          - validFor: validFor
            defaultValue: true
            active: true
            label: Bishop
            value: Bishop
          - validFor: validFor
            defaultValue: true
            active: true
            label: Bishop
            value: Bishop
          aiPredictionField: true
          filterable: true
          maskType: maskType
          queryByDistance: true
          caseSensitive: true
          aggregatable: true
          referenceTo:
          - User
          - User
          soapType: tns:ID
          unique: true
          name: Id
          highScaleNumber: true
          idLookup: true
          displayLocationInDecimal: true
          defaultedOnCreate: true
          updateable: true
          deprecatedAndHidden: true
          byteLength: 18
          scale: 0
          polymorphicForeignKey: true
          nillable: true
          htmlFormatted: true
          referenceTargetField: referenceTargetField
          cascadeDelete: true
          mask: mask
          permissionable: true
          relationshipOrder: relationshipOrder
          custom: true
          length: 18
          externalId: true
          dependentPicklist: true
          label: Contact ID
          sortable: true
          autoNumber: true
          filteredLookupInfo: filteredLookupInfo
          restrictedPicklist: true
          createable: true
          encrypted: true
          searchPrefilterable: true
          extraTypeInfo: extraTypeInfo
          groupable: true
          digits: 0
          formulaTreatNullNumberAsZero: true
        - defaultValue: defaultValue
          precision: 0
          compoundFieldName: compoundFieldName
          nameField: true
          type: id
          restrictedDelete: true
          relationshipName: relationshipName
          calculatedFormula: calculatedFormula
          controllerName: controllerName
          namePointing: true
          defaultValueFormula: defaultValueFormula
          calculated: true
          writeRequiresMasterRead: true
          inlineHelpText: inlineHelpText
          picklistValues:
          - validFor: validFor
            defaultValue: true
            active: true
            label: Bishop
            value: Bishop
          - validFor: validFor
            defaultValue: true
            active: true
            label: Bishop
            value: Bishop
          aiPredictionField: true
          filterable: true
          maskType: maskType
          queryByDistance: true
          caseSensitive: true
          aggregatable: true
          referenceTo:
          - User
          - User
          soapType: tns:ID
          unique: true
          name: Id
          highScaleNumber: true
          idLookup: true
          displayLocationInDecimal: true
          defaultedOnCreate: true
          updateable: true
          deprecatedAndHidden: true
          byteLength: 18
          scale: 0
          polymorphicForeignKey: true
          nillable: true
          htmlFormatted: true
          referenceTargetField: referenceTargetField
          cascadeDelete: true
          mask: mask
          permissionable: true
          relationshipOrder: relationshipOrder
          custom: true
          length: 18
          externalId: true
          dependentPicklist: true
          label: Contact ID
          sortable: true
          autoNumber: true
          filteredLookupInfo: filteredLookupInfo
          restrictedPicklist: true
          createable: true
          encrypted: true
          searchPrefilterable: true
          extraTypeInfo: extraTypeInfo
          groupable: true
          digits: 0
          formulaTreatNullNumberAsZero: true
        labelPlural: Contacts
        triggerable: true
      properties:
        activateable:
          type: boolean
        associateEntityType:
          nullable: true
          type: string
        associateParentEntity:
          nullable: true
          type: string
        compactLayoutable:
          type: boolean
        createable:
          type: boolean
        custom:
          type: boolean
        customSetting:
          type: boolean
        deepCloneable:
          type: boolean
        defaultImplementation:
          nullable: true
          type: string
        deletable:
          type: boolean
        deprecatedAndHidden:
          type: boolean
        extendedBy:
          nullable: true
          type: string
        extendsInterfaces:
          nullable: true
          type: string
        feedEnabled:
          type: boolean
        hasSubtypes:
          type: boolean
        implementedBy:
          nullable: true
          type: string
        implementsInterfaces:
          nullable: true
          type: string
        isInterface:
          type: boolean
        isSubtype:
          type: boolean
        keyPrefix:
          example: "3"
          type: string
        label:
          example: Contact
          type: string
        labelPlural:
          example: Contacts
          type: string
        layoutable:
          type: boolean
        listviewable:
          nullable: true
          type: string
        lookupLayoutable:
          nullable: true
          type: string
        mergeable:
          type: boolean
        mruEnabled:
          type: boolean
        name:
          example: Contact
          type: string
        networkScopeFieldName:
          nullable: true
          type: string
        queryable:
          type: boolean
        replicateable:
          type: boolean
        retrieveable:
          type: boolean
        searchLayoutable:
          type: boolean
        searchable:
          type: boolean
        sobjectDescribeOption:
          example: FULL
          type: string
        triggerable:
          type: boolean
        undeletable:
          type: boolean
        updateable:
          type: boolean
        namedLayoutInfos:
          items: {}
          type: array
        actionOverrides:
          items:
            $ref: '#/components/schemas/actionOverrides'
          type: array
        childRelationships:
          items:
            $ref: '#/components/schemas/childRelationships'
          type: array
        recordTypeInfos:
          items:
            $ref: '#/components/schemas/recordTypeInfo'
          type: array
        supportedScopes:
          items:
            $ref: '#/components/schemas/supportedScopes'
          type: array
        urls:
          type: object
        fields:
          items:
            $ref: '#/components/schemas/fieldDescribe'
          type: array
      type: object
    actionOverrides:
      example:
        formFactor: LARGE
        name: View
        pageId: 0M03b000000PGADCA4
        url: url
        isAvailableInTouch: true
      properties:
        formFactor:
          example: LARGE
          type: string
        isAvailableInTouch:
          type: boolean
        name:
          example: View
          type: string
        pageId:
          example: 0M03b000000PGADCA4
          type: string
        url:
          nullable: true
          type: string
      type: object
    childRelationships:
      example:
        relationshipName: Accounts__r
        field: Primary_Contact__c
        deprecatedAndHidden: true
        junctionReferenceTo:
        - "{}"
        - "{}"
        junctionIdListNames:
        - "{}"
        - "{}"
        childSObject: Account
        cascadeDelete: true
        restrictedDelete: true
      properties:
        cascadeDelete:
          type: boolean
        childSObject:
          example: Account
          type: string
        deprecatedAndHidden:
          type: boolean
        field:
          example: Primary_Contact__c
          type: string
        junctionIdListNames:
          items:
            type: string
          type: array
        junctionReferenceTo:
          items:
            type: string
          type: array
        relationshipName:
          example: Accounts__r
          type: string
        restrictedDelete:
          type: boolean
      type: object
    recordTypeInfoUrls:
      example:
        layout: /services/data/v56.0/sobjects/Contact/describe/layouts/012000000000000AAA
      properties:
        layout:
          example: /services/data/v56.0/sobjects/Contact/describe/layouts/012000000000000AAA
          type: string
      type: object
    recordTypeInfo:
      example:
        defaultRecordTypeMapping: true
        urls:
          layout: /services/data/v56.0/sobjects/Contact/describe/layouts/012000000000000AAA
        recordTypeId: 012000000000000AAA
        available: true
        name: Master
        active: true
        developerName: Master
        master: true
      properties:
        active:
          type: boolean
        available:
          type: boolean
        defaultRecordTypeMapping:
          type: boolean
        developerName:
          example: Master
          type: string
        master:
          type: boolean
        name:
          example: Master
          type: string
        recordTypeId:
          example: 012000000000000AAA
          type: string
        urls:
          $ref: '#/components/schemas/recordTypeInfoUrls'
      type: object
    supportedScopes:
      example:
        name: everything
        label: All contacts
      properties:
        label:
          example: All contacts
          type: string
        name:
          example: everything
          type: string
      type: object
    fieldDescribePicklist:
      example:
        validFor: validFor
        defaultValue: true
        active: true
        label: Bishop
        value: Bishop
      properties:
        active:
          type: boolean
        defaultValue:
          type: boolean
        label:
          example: Bishop
          type: string
        validFor:
          nullable: true
          type: string
        value:
          example: Bishop
          type: string
      type: object
    fieldDescribe:
      example:
        defaultValue: defaultValue
        precision: 0
        compoundFieldName: compoundFieldName
        nameField: true
        type: id
        restrictedDelete: true
        relationshipName: relationshipName
        calculatedFormula: calculatedFormula
        controllerName: controllerName
        namePointing: true
        defaultValueFormula: defaultValueFormula
        calculated: true
        writeRequiresMasterRead: true
        inlineHelpText: inlineHelpText
        picklistValues:
        - validFor: validFor
          defaultValue: true
          active: true
          label: Bishop
          value: Bishop
        - validFor: validFor
          defaultValue: true
          active: true
          label: Bishop
          value: Bishop
        aiPredictionField: true
        filterable: true
        maskType: maskType
        queryByDistance: true
        caseSensitive: true
        aggregatable: true
        referenceTo:
        - User
        - User
        soapType: tns:ID
        unique: true
        name: Id
        highScaleNumber: true
        idLookup: true
        displayLocationInDecimal: true
        defaultedOnCreate: true
        updateable: true
        deprecatedAndHidden: true
        byteLength: 18
        scale: 0
        polymorphicForeignKey: true
        nillable: true
        htmlFormatted: true
        referenceTargetField: referenceTargetField
        cascadeDelete: true
        mask: mask
        permissionable: true
        relationshipOrder: relationshipOrder
        custom: true
        length: 18
        externalId: true
        dependentPicklist: true
        label: Contact ID
        sortable: true
        autoNumber: true
        filteredLookupInfo: filteredLookupInfo
        restrictedPicklist: true
        createable: true
        encrypted: true
        searchPrefilterable: true
        extraTypeInfo: extraTypeInfo
        groupable: true
        digits: 0
        formulaTreatNullNumberAsZero: true
      properties:
        aggregatable:
          type: boolean
        aiPredictionField:
          type: boolean
        autoNumber:
          type: boolean
        byteLength:
          example: 18
          format: int32
          type: integer
        calculated:
          type: boolean
        calculatedFormula:
          nullable: true
          type: string
        cascadeDelete:
          type: boolean
        caseSensitive:
          type: boolean
        compoundFieldName:
          nullable: true
          type: string
        controllerName:
          nullable: true
          type: string
        createable:
          type: boolean
        custom:
          type: boolean
        defaultValue: {}
        defaultValueFormula:
          nullable: true
          type: string
        defaultedOnCreate:
          type: boolean
        dependentPicklist:
          type: boolean
        deprecatedAndHidden:
          type: boolean
        digits:
          example: 0
          format: int32
          type: integer
        displayLocationInDecimal:
          type: boolean
        encrypted:
          type: boolean
        externalId:
          type: boolean
        extraTypeInfo:
          nullable: true
          type: string
        filterable:
          type: boolean
        filteredLookupInfo:
          nullable: true
          type: object
        formulaTreatNullNumberAsZero:
          type: boolean
        groupable:
          type: boolean
        highScaleNumber:
          type: boolean
        htmlFormatted:
          type: boolean
        idLookup:
          type: boolean
        inlineHelpText:
          nullable: true
          type: string
        label:
          example: Contact ID
          type: string
        length:
          example: 18
          format: int32
          type: integer
        mask:
          nullable: true
          type: string
        maskType:
          nullable: true
          type: string
        name:
          example: Id
          type: string
        nameField:
          type: boolean
        namePointing:
          type: boolean
        nillable:
          type: boolean
        permissionable:
          type: boolean
        picklistValues:
          items:
            $ref: '#/components/schemas/fieldDescribePicklist'
          type: array
        polymorphicForeignKey:
          type: boolean
        precision:
          example: 0
          format: int32
          type: integer
        queryByDistance:
          type: boolean
        referenceTargetField:
          nullable: true
          type: string
        referenceTo:
          items:
            example: User
            type: string
          type: array
        relationshipName:
          nullable: true
          type: string
        relationshipOrder:
          format: int32
          nullable: true
          type: integer
        restrictedDelete:
          type: boolean
        restrictedPicklist:
          type: boolean
        scale:
          example: 0
          format: int32
          type: integer
        searchPrefilterable:
          type: boolean
        soapType:
          example: tns:ID
          type: string
        sortable:
          type: boolean
        type:
          $ref: '#/components/schemas/fieldType'
        unique:
          type: boolean
        updateable:
          type: boolean
        writeRequiresMasterRead:
          type: boolean
      type: object
    sObjectDescribes:
      example:
        maxBatchSize: 200
        sobjects:
        - null
        - null
        encoding: UTF-8
      properties:
        encoding:
          example: UTF-8
          type: string
        maxBatchSize:
          example: 200
          format: int32
          type: integer
        sobjects:
          items:
            $ref: '#/components/schemas/sObjectDescribe'
          type: array
    fieldType:
      enum:
      - address
      - anytype
      - base64
      - boolean
      - combobox
      - currency
      - datacategorygroupreference
      - date
      - datetime
      - double
      - email
      - encryptedstring
      - id
      - int
      - location
      - long
      - multipicklist
      - percent
      - phone
      - picklist
      - reference
      - string
      - textarea
      - time
      - url
      example: id
      type: string
    createRecordResult:
      example:
        success: true
        id: 001D000000IqhSLIAZ
        errors:
        - ""
        - ""
      properties:
        id:
          example: 001D000000IqhSLIAZ
          nullable: true
          type: string
        errors:
          items: {}
          nullable: false
          type: array
        success:
          example: true
          nullable: false
          type: boolean
    errors:
      items:
        $ref: '#/components/schemas/error'
      type: array
    error:
      properties:
        message:
          type: string
        errorCode:
          type: string
        fields:
          items:
            type: string
          type: array
      type: object
    EncodingType:
      description: "Use a compression header to compress a REST API request or response.\
        \ Compression reduces the bandwidth required for a request, although it requires\
        \ more processing power at your client. In most cases, this tradeoff benefits\
        \ the overall performance of your application. REST API supports the gzip\
        \ and deflate compression algorithms, as defined by the HTTP 1.1 specification.\
        \ If you’re unsure about which one to use, gzip is more common than deflate."
      enum:
      - gzip
      - deflate
      title: Encoding Type
      type: string
  securitySchemes:
    oAuth:
      description: This API uses OAuth 2 with various flows
      flows:
        clientCredentials:
          scopes: {}
          tokenUrl: /services/oauth2/token
        password:
          scopes: {}
          tokenUrl: /services/oauth2/token
      type: oauth2
